version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-app
    ports:
      - "3000:3000"
    environment:
      ENVIRONMENT: production
      PORT: 3000
      GIN_MODE: release
      DB_URL: host=db user=postgres password=postgres dbname=todo port=5432 sslmode=disable
    depends_on:
      - db